### ISSUE TITLE
Regarding maxout

### ISSUE THREAD

**Issue by NirLados** [HoldenWuLab/AT_Seg_3DCNN#1]
Hello,

I greatly appreciate your excellent work and the effort you've put into it. I have a question regarding the maxout function, which doesn't appear to be defined in the provided code. Could you please clarify how you implemented it?

Thank you in advance for your assistance,
Nir,

**Comment by ddthomas** [comment]
Hello, I have the same question as Nir. Thank you for any details you can provide about the maxout function.

**Comment by ddthomas** [comment]
> Hello, I have the same question as Nir. Thank you for any details you can provide about the maxout function.

Apologies, I did not see that you added it three days ago. Thank you.

**Comment by NirLados** [comment]
Hello,
I addressed this question to the authors of the code; they updated as you
saw.
Did you manage to implement the model?


Thanks,
Nir,

**Comment by sevgikafali** [comment]
Hi everyone,

I added the maxout function about a month ago but forgot to reply here... Sorry about that. It should work now. 

Best,
